/**
 * Rich mock data — present-time (2026), targeting 2027 passout batch.
 */

const now = Date.now();
const hoursAgo    = (h) => new Date(now - h * 3_600_000).toISOString();
const daysFromNow = (d) => new Date(now + d * 86_400_000).toISOString();

const MOCK_NOTIFICATIONS = [
  {
    id: 'mock-001',
    type: 'Placement',
    title: 'Google India — SWE On-Campus Drive 2026',
    message: 'Google India is visiting campus for their flagship Software Engineer (L3) hiring drive. This is a once-in-a-year opportunity for top performers. The process includes an online assessment, two technical rounds (DSA + System Design), and an HR round. Selected candidates will be offered a full-time role with joining in December 2026. Open to 2027 batch students.',
    createdAt: hoursAgo(1),
    deadline: daysFromNow(6),
    company: 'Google India',
    location: 'Bangalore / Hyderabad',
    eligibility: 'CSE, IT, ECE · 7.5+ CGPA · 2027 batch',
    ctc: '₹28–45 LPA',
    tags: ['DSA', 'System Design', 'Problem Solving'],
    actionLabel: 'Apply on Portal',
    actionUrl: '#',
    isNew: true,
  },
  {
    id: 'mock-002',
    type: 'Result',
    title: 'Semester 6 Results Declared — Jan–Apr 2026',
    message: 'Results for Semester 6 (January–April 2026) have been officially published on the university examination portal. Students can log in with their roll number to view subject-wise marks, internal assessment scores, and overall CGPA. Digitally signed mark sheets can be downloaded from the academic section. Students wishing to apply for revaluation must submit the form along with the prescribed fee within 5 working days.',
    createdAt: hoursAgo(3),
    deadline: daysFromNow(5),
    company: 'Examination Cell',
    location: 'University Portal',
    eligibility: 'All Semester 6 Students (2027 batch)',
    ctc: null,
    tags: ['Revaluation Open', 'Grade Card', 'CGPA'],
    actionLabel: 'View Result',
    actionUrl: '#',
    isNew: false,
  },
  {
    id: 'mock-003',
    type: 'Event',
    title: 'TechFest 2026 — Registrations Now Open!',
    message: "PingHub's Annual Technical Festival TechFest 2026 returns bigger than ever! This year features 16 competitive events across AI/ML, Web Dev, Robotics, Cloud Computing, and Competitive Programming. Prizes worth ₹6 Lakhs are up for grabs. Teams of 2-4 members allowed for most events. Chief Guest: VP Engineering, Microsoft India. Free registration for all enrolled students.",
    createdAt: hoursAgo(5),
    deadline: daysFromNow(18),
    company: 'Student Technical Council',
    location: 'Main Campus Auditorium',
    eligibility: 'Open to all students',
    prize: '₹6 Lakhs total prizes',
    tags: ['Hackathon', 'Robotics', 'AI/ML'],
    actionLabel: 'Register Now',
    actionUrl: '#',
    isNew: false,
  },
  {
    id: 'mock-004',
    type: 'Placement',
    title: 'Microsoft — 6-Month Paid Internship 2026',
    message: 'Microsoft is offering 6-month paid internships for pre-final year students (2027 batch). Roles: Software Development Engineer Intern and Data Science Intern. Interns will work on live Azure and Microsoft 365 products used by millions globally. Mentorship from senior engineers guaranteed. Strong PPO conversion rate — 78% of interns received full-time offers last year.',
    createdAt: hoursAgo(8),
    deadline: daysFromNow(10),
    company: 'Microsoft',
    location: 'Hyderabad (On-site)',
    eligibility: 'All branches · 8.0+ CGPA · 2027 batch',
    ctc: '₹80,000/month stipend',
    tags: ['Internship', 'SDE', 'PPO Opportunity'],
    actionLabel: 'Apply Now',
    actionUrl: '#',
    isNew: false,
  },
  {
    id: 'mock-005',
    type: 'Event',
    title: 'Guest Lecture: Generative AI in Industry — May 2026',
    message: "The Department of Computer Science is hosting Dr. Ananya Krishnan, Principal Research Scientist at Google DeepMind India, for an exclusive guest lecture on 'Generative AI: From Research to Real-World Applications'. Topics: LLMs, prompt engineering, AI safety, and career paths in AI research. Q&A and networking session to follow. Certificates of participation will be issued. Register fast — only 150 seats available.",
    createdAt: hoursAgo(12),
    deadline: daysFromNow(7),
    company: 'Dept. of Computer Science',
    location: 'Seminar Hall A, Block 3',
    eligibility: 'Open to all departments',
    prize: 'Participation Certificate',
    tags: ['AI/ML', 'Gen AI', 'Research'],
    actionLabel: 'Register',
    actionUrl: '#',
    isNew: false,
  },
  {
    id: 'mock-006',
    type: 'Result',
    title: 'Internal Assessment Marks — May 2026',
    message: 'Internal assessment marks for all even-semester courses have been uploaded to the student portal by the respective faculty. Verify your marks carefully. Discrepancies must be reported in writing to the department office within 3 working days — no claims will be entertained after the deadline. Consolidated mark sheets will be shared 2 weeks before the end-semester exams.',
    createdAt: hoursAgo(18),
    deadline: daysFromNow(3),
    company: 'Academic Section',
    location: 'Student Portal',
    eligibility: 'All students — Even Semester 2026',
    ctc: null,
    tags: ['Marks', 'Portal', 'Urgent'],
    actionLabel: 'Check Marks',
    actionUrl: '#',
    isNew: false,
  },
  {
    id: 'mock-007',
    type: 'Placement',
    title: 'Infosys — Systems Engineer Drive 2026',
    message: 'Infosys is conducting a campus recruitment drive for 2027 graduates across all engineering disciplines. Roles on offer: Systems Engineer (₹4.5 LPA) and Digital Specialist Engineer (₹9.5 LPA). Selection process: InfyTQ assessment → Technical Interview → HR round. InfyTQ certified students will be fast-tracked. Carry original mark sheets and ID proof on interview day.',
    createdAt: hoursAgo(24),
    deadline: daysFromNow(16),
    company: 'Infosys',
    location: 'Pan-India / Hybrid',
    eligibility: 'All branches · 60%+ aggregate · No active backlogs · 2027 batch',
    ctc: '₹4.5 LPA – ₹9.5 LPA',
    tags: ['Mass Drive', 'InfyTQ', 'All Branches'],
    actionLabel: 'Apply Now',
    actionUrl: '#',
    isNew: false,
  },
  {
    id: 'mock-008',
    type: 'Event',
    title: 'Cultural Fest "Euphoria 2026" — Day 2 Schedule',
    message: "Euphoria 2026 Day 1 was a massive success — 3,000+ students, 20 events, and an electrifying performance by Prateek Kuhad! Day 2 starts tomorrow at 9 AM. Highlights: Battle of Bands at the open-air amphitheatre, Street Dance Nationals qualifier, Fashion Showcase: 'Neon Roots'. Free entry with student ID. Food court open from 8 AM. Follow @PingHubCampus for live updates.",
    createdAt: hoursAgo(30),
    deadline: daysFromNow(1),
    company: 'Cultural Committee',
    location: 'Open Air Amphitheatre',
    eligibility: 'All enrolled students',
    prize: 'Trophies + ₹2 Lakh Cash Prizes',
    tags: ['Cultural', 'Music', 'Dance'],
    actionLabel: 'View Schedule',
    actionUrl: '#',
    isNew: false,
  },
  {
    id: 'mock-009',
    type: 'Result',
    title: 'GATE 2026 — Qualified Students List Released',
    message: '52 students from our institution qualified GATE 2026 — a new record! The complete list with AIR and scores is on the department website. GATE 2026 qualifiers are eligible for M.Tech admissions at IITs/NITs and PSU recruitment (BHEL, ONGC, IOCL, NTPC). Counselling starts June 2026. The placement cell will provide documentation support and mock interviews for PSU GDs.',
    createdAt: hoursAgo(36),
    deadline: daysFromNow(30),
    company: 'Examination Cell',
    location: 'Department Notice Board / Website',
    eligibility: 'GATE 2026 Qualifiers',
    ctc: null,
    tags: ['GATE 2026', 'M.Tech', 'PSU Jobs'],
    actionLabel: 'View Qualified List',
    actionUrl: '#',
    isNew: false,
  },
  {
    id: 'mock-010',
    type: 'Placement',
    title: 'Amazon — SDE-1 Off-Campus Drive 2026',
    message: "Amazon India is hiring SDE-1 engineers for Hyderabad and Bangalore. Open to 2026 graduates and 2027 final-year students. Hiring process: HackerRank online assessment (2 hrs) → 2 virtual technical rounds → Bar Raiser round → Offer. Strong DSA and object-oriented design skills required. Students with prior Amazon internship experience are preferred but not mandatory.",
    createdAt: hoursAgo(48),
    deadline: daysFromNow(13),
    company: 'Amazon',
    location: 'Hyderabad / Bangalore',
    eligibility: 'CSE, IT · 65%+ · 2026 or 2027 batch',
    ctc: '₹24–32 LPA',
    tags: ['SDE', 'DSA', 'Off-Campus'],
    actionLabel: 'Apply on Portal',
    actionUrl: '#',
    isNew: false,
  },
  {
    id: 'mock-011',
    type: 'Event',
    title: 'Workshop: Full Stack Dev with Next.js 15 — May 2026',
    message: "A 2-day intensive workshop on full stack development using Next.js 15 (App Router), Prisma ORM, Supabase, and Vercel deployment — delivered by senior engineers from Razorpay's frontend platform team. Day 1: Next.js fundamentals, RSC, and database integration. Day 2: Auth (NextAuth v5), CI/CD, and production monitoring. Bring your laptop. Starter repo shared 2 days before.",
    createdAt: hoursAgo(54),
    deadline: daysFromNow(20),
    company: 'Razorpay Engineers',
    location: 'CS Lab 201, Block 2',
    eligibility: 'Basic React knowledge required · 2027 batch preferred',
    prize: 'Completion Certificate + Razorpay LinkedIn Badge',
    tags: ['Next.js 15', 'Full Stack', 'Supabase'],
    actionLabel: 'Register (50 seats)',
    actionUrl: '#',
    isNew: false,
  },
  {
    id: 'mock-012',
    type: 'Placement',
    title: 'Deloitte USI — Consulting Analyst 2026',
    message: 'Deloitte USI is recruiting Consulting Analysts for their Technology & Transformation practice in Bangalore and Mumbai. You will work with Fortune 500 clients on digital transformation projects. The hiring process: aptitude test → group discussion → case study presentation → two interviews. All engineering branches welcome. Graduates with strong analytical and communication skills are encouraged to apply.',
    createdAt: hoursAgo(72),
    deadline: daysFromNow(31),
    company: 'Deloitte USI',
    location: 'Bangalore / Mumbai',
    eligibility: 'All branches · 65%+ · Good communication · 2027 batch',
    ctc: '₹7.5 LPA + performance bonus',
    tags: ['Consulting', 'Business Tech', 'All Branches'],
    actionLabel: 'Apply Now',
    actionUrl: '#',
    isNew: false,
  },
];

export default MOCK_NOTIFICATIONS;
